import { Country } from "@/types/Country";

const countriesList: Country[] = [
  { name: "Afghanistan", isoCode: "AF", currency: "AFN", id: "1" },
  { name: "Åland Islands", isoCode: "AX", currency: "EUR", id: "2" },
  { name: "Albania", isoCode: "AL", currency: "ALL", id: "3" },
  { name: "Algeria", isoCode: "DZ", currency: "DZD", id: "4" },
  { name: "American Samoa", isoCode: "AS", currency: "USD", id: "5" },
  { name: "Andorra", isoCode: "AD", currency: "EUR", id: "6" },
  { name: "Angola", isoCode: "AO", currency: "AOA", id: "7" },
  { name: "Argentina", isoCode: "AR", currency: "ARS", id: "8" },
  { name: "Armenia", isoCode: "AM", currency: "AMD", id: "9" },
  { name: "Aruba", isoCode: "AW", currency: "AWG", id: "10" },
  { name: "Australia", isoCode: "AU", currency: "AUD", id: "11" },
  { name: "Austria", isoCode: "AT", currency: "EUR", id: "12" },
  { name: "Azerbaijan", isoCode: "AZ", currency: "AZN", id: "13" },
  { name: "Bahamas", isoCode: "BS", currency: "BSD", id: "14" },
  { name: "Bahrain", isoCode: "BH", currency: "BHD", id: "15" },
  { name: "Bangladesh", isoCode: "BD", currency: "BDT", id: "16" },
  { name: "Barbados", isoCode: "BB", currency: "BBD", id: "17" },
  { name: "Belarus", isoCode: "BY", currency: "BYR", id: "18" },
  { name: "Belgium", isoCode: "BE", currency: "EUR", id: "19" },
  { name: "Belize", isoCode: "BZ", currency: "BZD", id: "20" },
  { name: "Benin", isoCode: "BJ", currency: "XOF", id: "21" },
  { name: "Bermuda", isoCode: "BM", currency: "BMD", id: "22" },
  { name: "Bhutan", isoCode: "BT", currency: "INR", id: "23" },
  {
    name: "Bolivia, Plurinational State Of",
    isoCode: "BO",
    currency: "BOB",
    id: "24",
  },
  {
    name: "Bonaire, Saint Eustatius And Saba",
    isoCode: "BQ",
    currency: "USD",
    id: "25",
  },
  {
    name: "Bosnia & Herzegovina",
    isoCode: "BA",
    currency: "BAM",
    id: "26",
  },
  { name: "Botswana", isoCode: "BW", currency: "BWP", id: "27" },
  { name: "Bouvet Island", isoCode: "BV", currency: "NOK", id: "28" },
  { name: "Brazil", isoCode: "BR", currency: "BRL", id: "29" },
  {
    name: "British Indian Ocean Territory",
    isoCode: "IO",
    currency: "USD",
    id: "30",
  },
  {
    name: "Brunei Darussalam",
    isoCode: "BN",
    currency: "BND",
    id: "31",
  },
  { name: "Bulgaria", isoCode: "BG", currency: "BGN", id: "32" },
  { name: "Burkina Faso", isoCode: "BF", currency: "XOF", id: "33" },
  { name: "Burundi", isoCode: "BI", currency: "BIF", id: "34" },
  { name: "Cabo Verde", isoCode: "CV", currency: "CVE", id: "35" },
  { name: "Cambodia", isoCode: "KH", currency: "KHR", id: "36" },
  { name: "Cameroon", isoCode: "CM", currency: "XAF", id: "37" },
  { name: "Canada", isoCode: "CA", currency: "CAD", id: "38" },
  { name: "Canary Islands", isoCode: "IC", currency: "EUR", id: "39" },
  { name: "Cayman Islands", isoCode: "KY", currency: "KYD", id: "40" },
  {
    name: "Central African Republic",
    isoCode: "CF",
    currency: "XAF",
    id: "41",
  },
  { name: "Ceuta, Mulilla", isoCode: "EA", currency: "EUR", id: "42" },
  { name: "Chad", isoCode: "TD", currency: "XAF", id: "43" },
  { name: "Chile", isoCode: "CL", currency: "CLP", id: "44" },
  { name: "China", isoCode: "CN", currency: "CNY", id: "45" },
  {
    name: "Christmas Island",
    isoCode: "CX",
    currency: "AUD",
    id: "46",
  },
  {
    name: "Clipperton Island",
    isoCode: "CP",
    currency: "EUR",
    id: "47",
  },
  {
    name: "Cocos (Keeling) Islands",
    isoCode: "CC",
    currency: "AUD",
    id: "48",
  },
  { name: "Colombia", isoCode: "CO", currency: "COP", id: "49" },
  { name: "Comoros", isoCode: "KM", currency: "KMF", id: "50" },
  { name: "Cook Islands", isoCode: "CK", currency: "NZD", id: "51" },
  { name: "Costa Rica", isoCode: "CR", currency: "CRC", id: "52" },
  { name: "Cote d'Ivoire", isoCode: "CI", currency: "XOF", id: "53" },
  { name: "Croatia", isoCode: "HR", currency: "HRK", id: "54" },
  { name: "Cuba", isoCode: "CU", currency: "CUP", id: "55" },
  { name: "Curacao", isoCode: "CW", currency: "ANG", id: "56" },
  { name: "Cyprus", isoCode: "CY", currency: "EUR", id: "57" },
  { name: "Czech Republic", isoCode: "CZ", currency: "CZK", id: "58" },
  {
    name: "Democratic Republic Of Congo",
    isoCode: "CD",
    currency: "CDF",
    id: "59",
  },
  { name: "Denmark", isoCode: "DK", currency: "DKK", id: "60" },
  { name: "Diego Garcia", isoCode: "DG", currency: "USD", id: "61" },
  { name: "Djibouti", isoCode: "DJ", currency: "DJF", id: "62" },
  {
    name: "Dominican Republic",
    isoCode: "DO",
    currency: "DOP",
    id: "63",
  },
  { name: "East Timor", isoCode: "TL", currency: "USD", id: "64" },
  { name: "Ecuador", isoCode: "EC", currency: "USD", id: "65" },
  { name: "Egypt", isoCode: "EG", currency: "EGP", id: "66" },
  { name: "El Salvador", isoCode: "SV", currency: "USD", id: "67" },
  {
    name: "Equatorial Guinea",
    isoCode: "GQ",
    currency: "XAF",
    id: "68",
  },
  { name: "Eritrea", isoCode: "ER", currency: "ERN", id: "69" },
  { name: "Estonia", isoCode: "EE", currency: "EUR", id: "70" },
  { name: "Ethiopia", isoCode: "ET", currency: "ETB", id: "71" },
  { name: "European Union", isoCode: "EU", currency: "EUR", id: "72" },
  {
    name: "Falkland Islands",
    isoCode: "FK",
    currency: "FKP",
    id: "73",
  },
  { name: "Faroe Islands", isoCode: "FO", currency: "DKK", id: "74" },
  { name: "Fiji", isoCode: "FJ", currency: "FJD", id: "75" },
  { name: "Finland", isoCode: "FI", currency: "EUR", id: "76" },
  { name: "France", isoCode: "FR", currency: "EUR", id: "77" },
  {
    name: "France, Metropolitan",
    isoCode: "FX",
    currency: "EUR",
    id: "78",
  },
  { name: "French Guiana", isoCode: "GF", currency: "EUR", id: "79" },
  {
    name: "French Polynesia",
    isoCode: "PF",
    currency: "XPF",
    id: "80",
  },
  {
    name: "French Southern Territories",
    isoCode: "TF",
    currency: "EUR",
    id: "81",
  },
  { name: "Gabon", isoCode: "GA", currency: "XAF", id: "82" },
  { name: "Gambia", isoCode: "GM", currency: "GMD", id: "83" },
  { name: "Georgia", isoCode: "GE", currency: "GEL", id: "84" },
  { name: "Germany", isoCode: "DE", currency: "EUR", id: "85" },
  { name: "Ghana", isoCode: "GH", currency: "GHS", id: "86" },
  { name: "Gibraltar", isoCode: "GI", currency: "GIP", id: "87" },
  { name: "Greece", isoCode: "GR", currency: "EUR", id: "88" },
  { name: "Greenland", isoCode: "GL", currency: "DKK", id: "89" },
  { name: "Guadeloupe", isoCode: "GP", currency: "EUR", id: "90" },
  { name: "Guam", isoCode: "GU", currency: "USD", id: "91" },
  { name: "Guatemala", isoCode: "GT", currency: "GTQ", id: "92" },
  { name: "Guernsey", isoCode: "GG", currency: "GBP", id: "93" },
  { name: "Guinea", isoCode: "GN", currency: "GNF", id: "94" },
  { name: "Guinea-bissau", isoCode: "GW", currency: "XOF", id: "95" },
  { name: "Guyana", isoCode: "GY", currency: "GYD", id: "96" },
  { name: "Haiti", isoCode: "HT", currency: "HTG", id: "97" },
  {
    name: "Heard Island And McDonald Islands",
    isoCode: "HM",
    currency: "AUD",
    id: "98",
  },
  { name: "Honduras", isoCode: "HN", currency: "HNL", id: "99" },
  { name: "Hong Kong", isoCode: "HK", currency: "HKD", id: "100" },
  { name: "Hungary", isoCode: "HU", currency: "HUF", id: "101" },
  { name: "Iceland", isoCode: "IS", currency: "ISK", id: "102" },
  { name: "India", isoCode: "IN", currency: "INR", id: "103" },
  { name: "Indonesia", isoCode: "ID", currency: "IDR", id: "104" },
  {
    name: "Iran, Islamic Republic Of",
    isoCode: "IR",
    currency: "IRR",
    id: "105",
  },
  { name: "Iraq", isoCode: "IQ", currency: "IQD", id: "106" },
  { name: "Ireland", isoCode: "IE", currency: "EUR", id: "107" },
  { name: "Isle Of Man", isoCode: "IM", currency: "GBP", id: "108" },
  { name: "Israel", isoCode: "IL", currency: "ILS", id: "109" },
  { name: "Italy", isoCode: "IT", currency: "EUR", id: "110" },
  { name: "Jamaica", isoCode: "JM", currency: "JMD", id: "111" },
  { name: "Japan", isoCode: "JP", currency: "JPY", id: "112" },
  { name: "Jersey", isoCode: "JE", currency: "GBP", id: "113" },
  { name: "Jordan", isoCode: "JO", currency: "JOD", id: "114" },
  { name: "Kazakhstan", isoCode: "KZ", currency: "KZT", id: "115" },
  { name: "Kenya", isoCode: "KE", currency: "KES", id: "116" },
  { name: "Kiribati", isoCode: "KI", currency: "AUD", id: "117" },
  {
    name: "Korea, Democratic People's Republic Of",
    isoCode: "KP",
    currency: "KPW",
    id: "118",
  },
  {
    name: "Korea, Republic Of",
    isoCode: "KR",
    currency: "KRW",
    id: "119",
  },
  { name: "Kuwait", isoCode: "KW", currency: "KWD", id: "120" },
  { name: "Kyrgyzstan", isoCode: "KG", currency: "KGS", id: "121" },
  {
    name: "Lao People's Democratic Republic",
    isoCode: "LA",
    currency: "LAK",
    id: "122",
  },
  { name: "Latvia", isoCode: "LV", currency: "EUR", id: "123" },
  { name: "Lebanon", isoCode: "LB", currency: "LBP", id: "124" },
  { name: "Lesotho", isoCode: "LS", currency: "LSL", id: "125" },
  { name: "Liberia", isoCode: "LR", currency: "LRD", id: "126" },
  { name: "Libya", isoCode: "LY", currency: "LYD", id: "127" },
  { name: "Liechtenstein", isoCode: "LI", currency: "CHF", id: "128" },
  { name: "Lithuania", isoCode: "LT", currency: "EUR", id: "129" },
  { name: "Luxembourg", isoCode: "LU", currency: "EUR", id: "130" },
  { name: "Macao", isoCode: "MO", currency: "MOP", id: "131" },
  {
    name: "Macedonia, The Former Yugoslav Republic Of",
    isoCode: "MK",
    currency: "MKD",
    id: "132",
  },
  { name: "Madagascar", isoCode: "MG", currency: "MGA", id: "133" },
  { name: "Malawi", isoCode: "MW", currency: "MWK", id: "134" },
  { name: "Malaysia", isoCode: "MY", currency: "MYR", id: "135" },
  { name: "Maldives", isoCode: "MV", currency: "MVR", id: "136" },
  { name: "Mali", isoCode: "ML", currency: "XOF", id: "137" },
  { name: "Malta", isoCode: "MT", currency: "EUR", id: "138" },
  {
    name: "Marshall Islands",
    isoCode: "MH",
    currency: "USD",
    id: "139",
  },
  { name: "Martinique", isoCode: "MQ", currency: "EUR", id: "140" },
  { name: "Mauritania", isoCode: "MR", currency: "MRO", id: "141" },
  { name: "Mauritius", isoCode: "MU", currency: "MUR", id: "142" },
  { name: "Mayotte", isoCode: "YT", currency: "EUR", id: "143" },
  { name: "Mexico", isoCode: "MX", currency: "MXN", id: "144" },
  {
    name: "Micronesia, Federated States Of",
    isoCode: "FM",
    currency: "USD",
    id: "145",
  },
  { name: "Moldova", isoCode: "MD", currency: "MDL", id: "146" },
  { name: "Monaco", isoCode: "MC", currency: "EUR", id: "147" },
  { name: "Mongolia", isoCode: "MN", currency: "MNT", id: "148" },
  { name: "Montenegro", isoCode: "ME", currency: "EUR", id: "149" },
  { name: "Morocco", isoCode: "MA", currency: "MAD", id: "150" },
  { name: "Mozambique", isoCode: "MZ", currency: "MZN", id: "151" },
  { name: "Myanmar", isoCode: "MM", currency: "MMK", id: "152" },
  { name: "Namibia", isoCode: "NA", currency: "NAD", id: "153" },
  { name: "Nauru", isoCode: "NR", currency: "AUD", id: "154" },
  { name: "Nepal", isoCode: "NP", currency: "NPR", id: "155" },
  { name: "Netherlands", isoCode: "NL", currency: "EUR", id: "156" },
  { name: "New Caledonia", isoCode: "NC", currency: "XPF", id: "157" },
  { name: "New Zealand", isoCode: "NZ", currency: "NZD", id: "158" },
  { name: "Nicaragua", isoCode: "NI", currency: "NIO", id: "159" },
  { name: "Niger", isoCode: "NE", currency: "XOF", id: "160" },
  { name: "Nigeria", isoCode: "NG", currency: "NGN", id: "161" },
  { name: "Niue", isoCode: "NU", currency: "NZD", id: "162" },
  { name: "Norfolk Island", isoCode: "NF", currency: "AUD", id: "163" },
  {
    name: "Northern Mariana Islands",
    isoCode: "MP",
    currency: "USD",
    id: "164",
  },
  { name: "Norway", isoCode: "NO", currency: "NOK", id: "165" },
  { name: "Oman", isoCode: "OM", currency: "OMR", id: "166" },
  { name: "Pakistan", isoCode: "PK", currency: "PKR", id: "167" },
  { name: "Palau", isoCode: "PW", currency: "USD", id: "168" },
  {
    name: "Palestinian Territory, Occupied",
    isoCode: "PS",
    currency: "JOD",
    id: "169",
  },
  { name: "Panama", isoCode: "PA", currency: "PAB", id: "170" },
  {
    name: "Papua New Guinea",
    isoCode: "PG",
    currency: "PGK",
    id: "171",
  },
  { name: "Paraguay", isoCode: "PY", currency: "PYG", id: "172" },
  { name: "Peru", isoCode: "PE", currency: "PEN", id: "173" },
  { name: "Philippines", isoCode: "PH", currency: "PHP", id: "174" },
  { name: "Pitcairn", isoCode: "PN", currency: "NZD", id: "175" },
  { name: "Poland", isoCode: "PL", currency: "PLN", id: "176" },
  { name: "Portugal", isoCode: "PT", currency: "EUR", id: "177" },
  { name: "Puerto Rico", isoCode: "PR", currency: "USD", id: "178" },
  { name: "Qatar", isoCode: "QA", currency: "QAR", id: "179" },
  {
    name: "Republic Of Congo",
    isoCode: "CG",
    currency: "XAF",
    id: "180",
  },
  { name: "Reunion", isoCode: "RE", currency: "EUR", id: "181" },
  { name: "Romania", isoCode: "RO", currency: "RON", id: "182" },
  {
    name: "Russian Federation",
    isoCode: "RU",
    currency: "RUB",
    id: "183",
  },
  { name: "Rwanda", isoCode: "RW", currency: "RWF", id: "184" },
  {
    name: "Saint Barthélemy",
    isoCode: "BL",
    currency: "EUR",
    id: "185",
  },
  {
    name: "Saint Helena, Ascension And Tristan Da Cunha",
    isoCode: "SH",
    currency: "SHP",
    id: "186",
  },
  { name: "Saint Martin", isoCode: "MF", currency: "EUR", id: "187" },
  {
    name: "Saint Pierre And Miquelon",
    isoCode: "PM",
    currency: "EUR",
    id: "188",
  },
  { name: "Samoa", isoCode: "WS", currency: "WST", id: "189" },
  { name: "San Marino", isoCode: "SM", currency: "EUR", id: "190" },
  {
    name: "São Tomé and Príncipe",
    isoCode: "ST",
    currency: "STD",
    id: "191",
  },
  { name: "Saudi Arabia", isoCode: "SA", currency: "SAR", id: "192" },
  { name: "Senegal", isoCode: "SN", currency: "XOF", id: "193" },
  { name: "Serbia", isoCode: "RS", currency: "RSD", id: "194" },
  { name: "Seychelles", isoCode: "SC", currency: "SCR", id: "195" },
  { name: "Sierra Leone", isoCode: "SL", currency: "SLL", id: "196" },
  { name: "Singapore", isoCode: "SG", currency: "SGD", id: "197" },
  { name: "Sint Maarten", isoCode: "SX", currency: "ANG", id: "198" },
  { name: "Slovakia", isoCode: "SK", currency: "EUR", id: "199" },
  { name: "Slovenia", isoCode: "SI", currency: "EUR", id: "200" },
  {
    name: "Solomon Islands",
    isoCode: "SB",
    currency: "SBD",
    id: "201",
  },
  { name: "Somalia", isoCode: "SO", currency: "SOS", id: "202" },
  { name: "South Africa", isoCode: "ZA", currency: "ZAR", id: "203" },
  {
    name: "South Georgia And The South Sandwich Islands",
    isoCode: "GS",
    currency: "GBP",
    id: "204",
  },
  { name: "South Sudan", isoCode: "SS", currency: "SSP", id: "205" },
  { name: "Spain", isoCode: "ES", currency: "EUR", id: "206" },
  { name: "Sri Lanka", isoCode: "LK", currency: "LKR", id: "207" },
  { name: "Sudan", isoCode: "SD", currency: "SDG", id: "208" },
  { name: "Suriname", isoCode: "SR", currency: "SRD", id: "209" },
  {
    name: "Svalbard And Jan Mayen",
    isoCode: "SJ",
    currency: "NOK",
    id: "210",
  },
  { name: "Swaziland", isoCode: "SZ", currency: "SZL", id: "211" },
  { name: "Sweden", isoCode: "SE", currency: "SEK", id: "212" },
  { name: "Switzerland", isoCode: "CH", currency: "CHF", id: "213" },
  {
    name: "Syrian Arab Republic",
    isoCode: "SY",
    currency: "SYP",
    id: "214",
  },
  {
    name: "Taiwan, Province Of China",
    isoCode: "TW",
    currency: "TWD",
    id: "215",
  },
  { name: "Tajikistan", isoCode: "TJ", currency: "TJS", id: "216" },
  {
    name: "Tanzania, United Republic Of",
    isoCode: "TZ",
    currency: "TZS",
    id: "217",
  },
  { name: "Thailand", isoCode: "TH", currency: "THB", id: "218" },
  { name: "Togo", isoCode: "TG", currency: "XOF", id: "219" },
  { name: "Tokelau", isoCode: "TK", currency: "NZD", id: "220" },
  { name: "Tonga", isoCode: "TO", currency: "TOP", id: "221" },
  {
    name: "Trinidad And Tobago",
    isoCode: "TT",
    currency: "TTD",
    id: "222",
  },
  {
    name: "Tristan de Cunha",
    isoCode: "TA",
    currency: "GBP",
    id: "223",
  },
  { name: "Tunisia", isoCode: "TN", currency: "TND", id: "224" },
  { name: "Turkey", isoCode: "TR", currency: "TRY", id: "225" },
  { name: "Turkmenistan", isoCode: "TM", currency: "TMT", id: "226" },
  {
    name: "Turks And Caicos Islands",
    isoCode: "TC",
    currency: "USD",
    id: "227",
  },
  { name: "Tuvalu", isoCode: "TV", currency: "AUD", id: "228" },
  { name: "Uganda", isoCode: "UG", currency: "UGX", id: "229" },
  { name: "Ukraine", isoCode: "UA", currency: "UAH", id: "230" },
  {
    name: "United Arab Emirates",
    isoCode: "AE",
    currency: "AED",
    id: "231",
  },
  { name: "United Kingdom", isoCode: "GB", currency: "GBP", id: "232" },
  { name: "United Kingdom", isoCode: "UK", currency: "GBP", id: "233" },
  { name: "United States", isoCode: "US", currency: "USD", id: "234" },
  {
    name: "United States Minor Outlying Islands",
    isoCode: "UM",
    currency: "USD",
    id: "235",
  },
  { name: "Uruguay", isoCode: "UY", currency: "UYU", id: "236" },
  { name: "USSR", isoCode: "SU", currency: "RUB", id: "237" },
  { name: "Uzbekistan", isoCode: "UZ", currency: "UZS", id: "238" },
  { name: "Vanuatu", isoCode: "VU", currency: "VUV", id: "239" },
  {
    name: "Vatican City State",
    isoCode: "VA",
    currency: "EUR",
    id: "240",
  },
  {
    name: "Venezuela, Bolivarian Republic Of",
    isoCode: "VE",
    currency: "VEF",
    id: "241",
  },
  { name: "Viet Nam", isoCode: "VN", currency: "VND", id: "242" },
  {
    name: "Virgin Islands (British)",
    isoCode: "VG",
    currency: "USD",
    id: "243",
  },
  {
    name: "Virgin Islands (US)",
    isoCode: "VI",
    currency: "USD",
    id: "244",
  },
  {
    name: "Wallis And Futuna",
    isoCode: "WF",
    currency: "XPF",
    id: "245",
  },
  { name: "Western Sahara", isoCode: "EH", currency: "MAD", id: "246" },
  { name: "Yemen", isoCode: "YE", currency: "YER", id: "247" },
  { name: "Zambia", isoCode: "ZM", currency: "ZMW", id: "248" },
  { name: "Zimbabwe", isoCode: "ZW", currency: "USD", id: "249" },
];

export default countriesList;
